import json
from typing import Any, Optional

import litellm


class LLMClient:
    """
    This class is used to make calls to any LLM API supported by LiteLLM.

    Parameters
    ----------
    model : str
        Name of the model to use.
    api_key : str
        API key used to authenticate access to the LLM model.
    max_tokens : Optional[int], default=None
        Maximum token limit that the response can generate. If ``None``, the model's default value is used.
    temperature : Optional[float], default=0.0
        Temperature value used to control randomness in generation.
    **kwargs
        Additional arguments supported by LiteLLM depending on the selected model.
    """

    def __init__(
        self,
        model: str,
        api_key: str,
        max_tokens: Optional[int] = None,
        temperature: Optional[float] = None,
        **kwargs: Any,
    ) -> None:
        self.model = model
        self.api_key = api_key
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.extra_args = kwargs

    def llm_response(self, messages: list) -> str:
        """
        Generates a text response using the configured LLM model.

        Parameters
        ----------
        messages : list
            A list of messages that make up the conversation so far. Depending on the model you use,
            different message types (modalities) may be supported, such as text, images, and audio.

        Returns
        -------
        str
            Response generated by the LLM model.
        """
        response = litellm.completion(
            model=self.model,
            messages=messages,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
            api_key=self.api_key,
            **self.extra_args,
        )
        return response["choices"][0]["message"]["content"]

    def llm_response_json(self, messages: list) -> dict:
        """Converts a text response generated by the LLM model into a valid JSON dictionary."""
        response = self.llm_response(messages)
        return self.to_json(response)

    @staticmethod
    def to_json(llm_response: str) -> dict:
        """
        Extracts and validates a JSON dictionary from a string returned by GPT.

        This function looks for the first opening ``{`` character and the last closing ``}`` character in the response
        and tries to interpret that segment as a JSON object. If braces are not found or deserialization fails,
        an error is raised.

        Parameters
        ----------
        llm_response : str
            Raw response generated by the LLM, expected to contain JSON.

        Returns
        -------
        dict
            JSON dictionary contained in the LLM response.
        """
        if "{" not in llm_response or "}" not in llm_response:
            raise ReponseFormatError("GPT output is not a dictionary.", response=llm_response)

        from_ = llm_response.index("{")
        to = llm_response.rindex("}") + 1
        json_candidate = llm_response[from_:to]
        try:
            return json.loads(json_candidate)
        except Exception:
            raise ReponseFormatError("GPT output is not a well structured dictionary", response=llm_response)


class ReponseFormatError(Exception):
    """Exception raised to indicate a formatting error in the LLM response."""

    def __init__(self, message: str, response: str) -> None:
        super().__init__(message)
        self.message = message
        self.response = response

    def __str__(self) -> str:
        return f"{self.message} (LLM reponse: {self.response})"
